spring.application.name=amazon-api-gateway

server.port=8099

# ==========================================
# EUREKA
# ==========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==========================================
# ACTUATOR
# ==========================================

management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=health,info,gateway

# ==========================================
# GATEWAY ROUTES
# ==========================================
# ORDER SERVICE
spring.cloud.gateway.server.webmvc.routes[0].id=order-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/order/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=CorrelationPropagation

# PRODUCT SERVICE
spring.cloud.gateway.server.webmvc.routes[1].id=product-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/product/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=CorrelationPropagation

# INVENTORY SERVICE
spring.cloud.gateway.server.webmvc.routes[2].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/inventory/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=CorrelationPropagation

# ==========================================
# LOGGING
# ==========================================

logging.level.com.amazon.amazon_api_gateway=DEBUG
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.loadbalancer=INFO

# ==========================================
# JWT
# ==========================================

jwt.secret=ThisIsMyVerySecureSecretKeyForJwtAuthentication123456789

# ==========================================
# Rate Limiting Configuration
# ==========================================

rate-limit.capacity=10
rate-limit.refill-tokens=10
rate-limit.refill-duration=60

rate-limit.cache-max-size=10000
rate-limit.cache-expiry-minutes=60

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [CorrelationID-%X{correlationId}] %-5level %logger{36} - %msg%n